WIP

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -124,16 +124,16 @@ runs:
               echo "ERROR: Failed to parse JSON specified in inputs.opschain_project_properties. Aborting."
               exit 1
           fi
-          cat<<EOF > ./.opschain.project.properties
-          ${{ inputs.opschain_project_properties }}
-          EOF
-          opschain project set-properties -p ${PROJECT_CODE} -f ./.opschain.project.properties --confirm
-          if [ $? -ne 0 ]; then
-            echo "ERROR: Failed to set Project level properties for OpsChain Project [ ${PROJECT_CODE} ]. Aborting."
-            exit 1
-          fi
-          rm -f ./.opschain.project.properties
         fi
+        cat<<EOF > ./.opschain.project.properties
+        ${{ inputs.opschain_project_properties }}
+        EOF
+        opschain project set-properties -p ${PROJECT_CODE} -f ./.opschain.project.properties --confirm
+        if [ $? -ne 0 ]; then
+          echo "ERROR: Failed to set Project level properties for OpsChain Project [ ${PROJECT_CODE} ]. Aborting."
+          exit 1
+        fi
+        rm -f ./.opschain.project.properties
 
         # Setup OpsChain Environment
         PROJECT_ID=$(curl -sL ${{ inputs.opschain_apiBaseUrl }}/projects/${PROJECT_CODE} --user ${{ inputs.opschain_username }}:${{ inputs.opschain_password }} | jq -r '.data.id')
